"""Add PlaidItem model

Revision ID: 02f66b68d39d
Revises: 01f800a773af
Create Date: 2025-04-17 03:31:46.238516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f66b68d39d'
down_revision = '01f800a773af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('institution_id', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_item_item_id'), ['item_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_item_item_id'))

    op.drop_table('plaid_item')
    # ### end Alembic commands ###
