"""Init table schema

Revision ID: 7408a93d3db3
Revises: 
Create Date: 2025-04-18 22:05:29.348679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7408a93d3db3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_subtype', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_external_id'), ['external_id'], unique=True)

    op.create_table('market_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_price_symbol'), ['symbol'], unique=True)

    op.create_table('plaid_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('institution_id', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sync_cursor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_item_item_id'), ['item_id'], unique=True)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_db_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('plaid_primary_category', sa.String(length=100), nullable=True),
    sa.Column('plaid_detailed_category', sa.String(length=100), nullable=True),
    sa.Column('plaid_category_id', sa.String(length=50), nullable=True),
    sa.Column('budget_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_db_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_db_id'), ['account_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_budget_category'), ['budget_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_plaid_account_id'), ['plaid_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_plaid_transaction_id'), ['plaid_transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_plaid_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_plaid_account_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_budget_category'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_db_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_item_item_id'))

    op.drop_table('plaid_item')
    with op.batch_alter_table('market_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_price_symbol'))

    op.drop_table('market_price')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_external_id'))

    op.drop_table('account')
    # ### end Alembic commands ###
