"""Add some budgeting, loan, salary stuff

Revision ID: bfde91541d63
Revises: 7408a93d3db3
Create Date: 2025-04-23 16:18:05.549064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfde91541d63'
down_revision = '7408a93d3db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('budget_category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expense_budget_category'), ['budget_category'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_salary_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_monthly_payment', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loan_original_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loan_interest_rate', sa.Numeric(precision=5, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('loan_interest_rate')
        batch_op.drop_column('loan_original_amount')
        batch_op.drop_column('loan_monthly_payment')

    op.drop_table('user_profile')
    with op.batch_alter_table('recurring_expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expense_budget_category'))

    op.drop_table('recurring_expense')
    # ### end Alembic commands ###
